src/live.asp.net/Pages/Admin/Index.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using live.asp.net.Models;
using live.asp.net.Services;

namespace live.asp.net.Pages.Admin
{
    public class IndexModel : PageModel
    {
        private readonly ILiveShowDetailsService _liveShowDetails;
        private readonly IMemoryCache _memoryCache;
        private readonly AppSettings _appSettings;
        private readonly IHostingEnvironment _env;
        private readonly IObjectMapper _mapper;
        private readonly ILogger _logger;

        public IndexModel(
            IHostingEnvironment env,
            ILiveShowDetailsService liveShowDetails,
            IMemoryCache memoryCache,
            IOptions<AppSettings> appSettings,
            IObjectMapper mapper,
            ILogger<IndexModel> logger)
        {
            _liveShowDetails = liveShowDetails;
            _memoryCache = memoryCache;
            _appSettings = appSettings.Value;
            _env = env;
            _mapper = mapper;
            _logger = logger;
        }

        [Display(Name = "Live Show Embed URL", Description = "URL for embedding the live show")]
        [DataType(DataType.Url)]
        public string LiveShowEmbedUrl { get; set; }

        [Display(Name = "Live Show HTML", Description = "HTML content for the live show")]
        [DataType(DataType.MultilineText)]
        public string LiveShowHtml { get; set; }

        [Display(Name = "Next Show Date/time", Description = "Exact date and time of the next live show in Pacific Time")]
        [DateAfterNow(TimeZoneId = "Pacific Standard Time")]
        public DateTime? NextShowDatePst { get; set; }

        [Display(Name = "Standby Message", Description = "Message to show on home page during show standby")]
        public string AdminMessage { get; set; }

        public string NextShowDateSuggestionPstAM { get; set; }

        public string NextShowDateSuggestionPstPM { get; set; }

        public bool ShowSuccessMessage => !string.IsNullOrEmpty(SuccessMessage);

        public AppSettings AppSettings { get; set; }

        public string EnvironmentName { get; set; }

        [TempData]
        public string SuccessMessage { get; set; }

        public async Task OnGetAsync()
        {
            var liveShowDetails = await _liveShowDetails.LoadAsync();

            UpdateModelProperties(liveShowDetails);
        }

        [ModelMetadataType(typeof(IndexModel))]
        public class Input
        {
            public string LiveShowEmbedUrl { get; set; }

            public string LiveShowHtml { get; set; }

            public DateTime? NextShowDatePst { get; set; }

            public string AdminMessage { get; set; }
        }

        public async Task<IActionResult> OnPostAsync(Input input)
        {
            var liveShowDetails = await _liveShowDetails.LoadAsync() ?? new LiveShowDetails();

            if (!ModelState.IsValid)
            {
                // Model validation error, just return and let the error render
                UpdateModelProperties(liveShowDetails);

                return Page();
            }

            if (!string.IsNullOrEmpty(input.LiveShowEmbedUrl) && input.LiveShowEmbedUrl.StartsWith("http://"))
            {
                input.LiveShowEmbedUrl = "https://" + input.LiveShowEmbedUrl.Substring("http://".Length);
            }

            TrackShowEvent(input, liveShowDetails);

            _mapper.Map(input, liveShowDetails);
            liveShowDetails.NextShowDateUtc = input.NextShowDatePst?.ConvertFromPtcToUtc();

            await _liveShowDetails.SaveAsync(liveShowDetails);

            SuccessMessage = "Live show details saved successfully!";

            return RedirectToPage();
        }

        public IActionResult OnPostClearCache()
        {
            _memoryCache.Remove(YouTubeShowsService.CacheKey);

            SuccessMessage = "YouTube cache cleared successfully!";

            return RedirectToPage();
        }

        private void UpdateModelProperties(LiveShowDetails liveShowDetails)
        {
            _mapper.Map(liveShowDetails, this);
            NextShowDatePst = liveShowDetails?.NextShowDateUtc?.ConvertFromUtcToPst();

            var nextTuesday = GetNextTuesday();
            NextShowDateSuggestionPstAM = nextTuesday.AddHours(10).ToString("MM/dd/yyyy HH:mm");
            NextShowDateSuggestionPstPM = nextTuesday.AddHours(15).AddMinutes(45).ToString("MM/dd/yyyy HH:mm");

            AppSettings = _appSettings;
            EnvironmentName = _env.EnvironmentName;
        }

        private DateTime GetNextTuesday()
        {
            var nowPst = DateTime.UtcNow.ConvertFromUtcToPst();
            var remainingDays = 7 - ((int)nowPst.DayOfWeek + 5) % 7;
            var nextTuesday = nowPst.AddDays(remainingDays);

            return nextTuesday.Date;
        }

        private static EventId _showStarted = new EventId(0, "Show Started");
        private static EventId _showEnded = new EventId(1, "Show Ended");

        private void TrackShowEvent(Input input, LiveShowDetails liveShowDetails)
        {
            if (_logger.IsEnabled(LogLevel.Information))
            {
                var showStarted = string.IsNullOrEmpty(liveShowDetails.LiveShowEmbedUrl) && !string.IsNullOrEmpty(input.LiveShowEmbedUrl);
                var showEnded = !string.IsNullOrEmpty(liveShowDetails.LiveShowEmbedUrl) && string.IsNullOrEmpty(input.LiveShowEmbedUrl);

                if (showStarted)
                {
                    _logger.LogInformation(_showStarted, "Show started streaming at {ShowEmbedUrl}", input.LiveShowEmbedUrl);
                }
                if (showEnded)
                {
                    _logger.LogInformation(_showEnded, "Show ended streaming at {ShowEmbedUrl}", liveShowDetails.LiveShowEmbedUrl);
                }
            }
        }
    }
}

src/live.asp.net/Pages/Admin/Index.cshtml
@page
@model IndexModel

@{
    ViewData["Title"] = "ASP.NET Community Standup Admin";
}

<ol class="breadcrumb">
    <li><a asp-page="/Index">Home</a></li>
    <li class="active">Admin</li>
</ol>

<div class="admin-screen">
    <h2>ASP.NET Community Standup Admin - @Model.EnvironmentName</h2>

    <form method="post" class="form-horizontal" role="form">
        <h4>Live Show Details</h4>
        <hr />
        @if (Model.ShowSuccessMessage)
        {
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                @Model.SuccessMessage
            </div>
        }
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="AdminMessage" class="col-md-3 control-label"></label>
            <div class="col-md-5">
                <input asp-for="AdminMessage" class="form-control" />
                <span asp-validation-for="AdminMessage" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LiveShowEmbedUrl" class="col-md-3 control-label"></label>
            <div class="col-md-5">
                <input asp-for="LiveShowEmbedUrl" class="form-control" />
                <span asp-validation-for="LiveShowEmbedUrl" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LiveShowHtml" class="col-md-3 control-label"></label>
            <div class="col-md-5">
                <textarea asp-for="LiveShowHtml" class="form-control html-input" rows="4"></textarea>
                <span asp-validation-for="LiveShowHtml" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group" id="nextShowDate">
            <label asp-for="NextShowDatePst" class="col-md-3 control-label"></label>
            <div class="col-md-5">
                <div class="input-group">
                    <input asp-for="NextShowDatePst" asp-format="{0:MM/dd/yyyy HH:mm}" type="text"
                        class="form-control" placeholder="MM/dd/yyyy HH:mm" maxlength="16" />
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Next Tuesday <span class="caret"></span></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#" data-suggestion="@Model.NextShowDateSuggestionPstAM">10:00 AM</a></li>
                            <li><a href="#" data-suggestion="@Model.NextShowDateSuggestionPstPM">3:45 PM</a></li>
                        </ul>
                    </div>
                    <span class="input-group-addon">
                        Pacific Time
                    </span>
                </div>
                <span asp-validation-for="NextShowDatePst" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>

    <form asp-page-handler="ClearCache" method="post" class="form-horizontal" role="form">
        <h4>YouTube Settings</h4>
        <hr />
        <div class="form-group">
            <label asp-for="AppSettings.YouTubePlaylistId" class="col-md-3 control-label"></label>
            <div class="col-md-4">
                <p class="form-control-static">@Model.AppSettings.YouTubePlaylistId</p>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AppSettings.YouTubeApplicationName" class="col-md-3 control-label"></label>
            <div class="col-md-3">
                <p class="form-control-static click-to-show" data-hidden-value="@Model.AppSettings.YouTubeApplicationName">click to show</p>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AppSettings.YouTubeApiKey" class="col-md-3 control-label"></label>
            <div class="col-md-4">
                <p class="form-control-static click-to-show" data-hidden-value="@Model.AppSettings.YouTubeApiKey">click to show</p>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn btn-danger">Clear YouTube Cache</button>
            </div>
        </div>
    </form>

    <div class="form-horizontal">
        <h4>Azure Storage Settings</h4>
        <hr />
        <div class="form-group">
            <label asp-for="AppSettings.AzureStorageConnectionString" class="col-md-3 control-label"></label>
            <div class="col-md-4">
                <p class="form-control-static click-to-show" data-hidden-value="@(Model.AppSettings.AzureStorageConnectionString ?? "[none]")">click to show</p>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AppSettings.AzureStorageContainerName" class="col-md-3 control-label"></label>
            <div class="col-md-4">
                <p class="form-control-static">@Model.AppSettings.AzureStorageContainerName</p>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="AppSettings.AzureStorageBlobName" class="col-md-3 control-label"></label>
            <div class="col-md-4">
                <p class="form-control-static">@Model.AppSettings.AzureStorageBlobName</p>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
    </environment>
    <partial name="_ValidationScripts" />
    <script>
        $(function () {
            $("p[data-hidden-value]")
                .click(function () {
                    var $self = $(this),
                        state = $self.data("state") || "hidden";
                    
                    if (state === "hidden") {
                        $self.text($self.data("hidden-value"));
                        $self.data("state", "showing");
                        $self.addClass("click-to-show-revealed");
                    } else {
                        $self.text("click to show");
                        $self.data("state", "hidden");
                        $self.removeClass("click-to-show-revealed");
                    }
                });
            
            var nextShowDateInput = $("#nextShowDate input");

            var suggestions = $("#nextShowDate a[data-suggestion]");

            suggestions
                .click(e => {
                    nextShowDateInput.val($(e.target).data("suggestion"));
                    e.preventDefault();
                });
        });
    </script>
}